---
title: "pull_data"
author: "Tarun"
date: "2/5/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dbplyr)
library(RMySQL)
library(dplyr)
library(tidyr)
library(lubridate)
library(readr)

con <- dbConnect(MySQL(),  
                 user="tnarasim",
                 password=rstudioapi::askForPassword("Database password"), 
                 host="shahlab-db1.stanford.edu", 
                 port=3306,
                 db = "stride7"
)

```


# Pull all visit data

```{r pull visit data}

## Pull first inpatient visit of every patient
### SHC_visit_de

visit_df <- dbGetQuery(con, 
"SELECT 
    `SHC_visit_de`.`patient_id`,
    `SHC_visit_de`.`contact_date`,
    `SHC_visit_de`.`enc_type_c`,
    `SHC_visit_de`.`department_id`,
    `SHC_visit_de`.`hosp_admsn_type_c`,
    `SHC_visit_de`.`visit_fc`,
    `SHC_visit_de`.`hosp_admsn_time`,
    `SHC_visit_de`.`hosp_disch_time`
FROM
    `stride7`.`SHC_visit_de`
WHERE
    YEAR(hosp_admsn_time) >= 2009
        AND hosp_admsn_time != '0000-00-00'
        AND hosp_disch_time != '0000-00-00';"       
)

dim(visit_df)

## Pull ADT table
### SHC_ADT_de

adt_df <- dbGetQuery(con,
"SELECT 
    `SHC_ADT_de`.`patient_id`, 
    `SHC_ADT_de`.`event_time`
FROM
    `stride7`.`SHC_ADT_de`
WHERE
        event_type_c=1 
OR      
        event_type_c=2; "   
)

# dbDisconnect(con)
```

# Pull first visit for each unique patient
```{r}
first_visit_df <- visit_df %>% 
  group_by(patient_id) %>% 
  filter(hosp_admsn_time == min(hosp_admsn_time)) %>% 
  filter(row_number(patient_id) == 1)

dim(first_visit_df)
```

# Filter against the SHC_visit_de table

```{r}
adt_df_uniq <- adt_df %>% 
  group_by(patient_id) %>% 
  filter(row_number(patient_id)==1) 

print(paste0("Row # ADT unique: ", dim(adt_df_uniq)[1] ) )

first_visit_df_filt <- first_visit_df %>% 
  inner_join(adt_df_uniq, by = c("patient_id" = "patient_id")) %>% 
  ungroup() %>% 
  mutate(hosp_admsn_time = as.POSIXct(hosp_admsn_time)) %>% 
  mutate(hosp_disch_time = as.POSIXct(hosp_disch_time))

write.csv(first_visit_df_filt, file = "/Users/Tarun/Documents/BIO_RESEARCH/pull_data/first_visit_df_filt.csv")

print(paste0("Row # first_visit_df_filt unique: ", dim(first_visit_df_filt)[1] ) )

```


# Grab ICU data
## Table: SHC_ADT_de 

```{r icu}
ICU_SHC_No_PACU <- c("2000251","2000254","2000255","2000262","9992000")

adt_icu_df <- con %>% 
  tbl("SHC_ADT_de") %>%
  filter(department_id %in% ICU_SHC_No_PACU) %>%
  select(patient_id, 
         event_type_c, 
         department_id, 
         event_time) %>% 
  filter(event_type_c==3 | event_type_c==4) %>% 
  arrange(patient_id, event_time) %>% 
  collect()
  

dim(adt_icu_df)
print(paste0("Number of unique ICU patients: ", n_distinct(adt_icu_df$patient_id)))
# View(filter(adt_icu_uniq, patient_id==425 | patient_id==1657))


adt_icu_uniq <- adt_icu_df %>% 
  mutate(entry = event_type_c==3) %>% 
  group_by(patient_id, entry) %>% 
  mutate( entryIndic = row_number(patient_id) == 1 & entry==1 ) %>% 
  ungroup() %>% group_by(patient_id) %>% 
  mutate(entryTime = ifelse(entryIndic==1, event_time, NA) ) %>% # find first entry time
  arrange(patient_id, entryTime) %>% 
  mutate(entryTime = first(entryTime)) %>% 
  filter( event_time > entryTime | entry==1 ) %>% 
  arrange(patient_id, event_time) %>% 
  ungroup() %>% group_by(patient_id, entry) %>%  # define exit time
  mutate(exitIndic = row_number(patient_id)==1 & entry==0 & event_time > entryTime) %>% 
  ungroup() %>% 
  filter(entryIndic == T | exitIndic == T) %>% 
  select(patient_id, 
         entryIndic, 
         exitIndic, 
         event_time, 
         department_id) %>% 
  group_by(patient_id) %>% 
  filter(n()==2) %>%  # keep only patients with exit AND entry
  filter( first(department_id) == last(department_id) ) %>%  # keep pats that enter/exit same dept
  select(-exitIndic) %>% 
  spread(entryIndic, event_time ) %>% 
  ungroup()

print(paste0("Number of unique ICU first visits: ", dim(adt_icu_uniq)[1]))
```

# Merge in medicine data 
## Tables: SHC_med_de, dictionary_medications_SHC_EPIC

```{r medicine}

first_visit_df_filt <- read_csv(
  "/Users/Tarun/Documents/BIO_RESEARCH/pull_data/first_visit_df_filt.csv"
)

first_visit_df_filt <- first_visit_df_filt %>% 
  select(-X1)


# Merge on by patient ID
## 17 minutes!!!
medications_df <- con %>% 
  tbl("SHC_med_de") %>% 
  select(patient_id, 
          medication_id, 
          order_time) %>% 
  collect() %>% 
  right_join(first_visit_df_filt, by = c("patient_id" = "patient_id")) %>% 
  mutate(order_time = as.POSIXct(order_time)) %>% # Fix the time variables
  mutate(order_time = floor_date(order_time, unit="days")) %>% 
  # mark which medications were inpatient
  mutate(inpat_med = 
           (hosp_admsn_time <= order_time & hosp_disch_time >= order_time)
         ) %>% 
  replace_na(list(inpat_med = F)) 


ptm <- proc.time()
write.csv(medications_df, 
          file = "/Users/Tarun/Documents/BIO_RESEARCH/pull_data/medications_df.csv")
proc.time() - ptm

# what proportion of medications found were assigned in first inpatient visit
sum(medications_df$inpat_med)/nrow(medications_df) 

medications_df <- read_csv(
  "/Users/Tarun/Documents/BIO_RESEARCH/pull_data/medications_df.csv"
) #80 seconds

medications_df <- medications_df %>% 
  select(-X1)

uniqueMeds <- read.csv(
  "/Users/Tarun/Documents/BIO_RESEARCH/exploratory_analysis/uniqueMeds.csv"
)

uniqueBsas <- uniqueMeds %>% 
  select(-X) %>% 
  rename(name = x)

# Merge on the medications dictionary
## medication_id links SHC_med_de to dictionary_medications_SHC_EPIC
med_dict_df <- con %>%
  tbl("dictionary_medications_SHC_EPIC") %>%
  select(rxcui_str, medication_id) %>% 
  mutate( bsa = rxcui_str %in% uniqueBsas$name==T ) %>% 
  filter(bsa==1) %>% # keep only BSA's
  select(-rxcui_str) %>% 
  group_by(medication_id) %>% 
  collect() %>% filter(row_number(medication_id) == 1) # keep unique medication_id
 # 3,107 medication_id values that are BSA


# merge medications dictionary onto medications-visit data
med_and_dict_df <- medications_df %>% 
  left_join(med_dict_df, by = "medication_id") %>% 
  replace_na(list(bsa = 0)) %>% 
  mutate(treatment = (bsa == 1 & inpat_med==T) ) %>% 
#  select(-X1) %>% 
  arrange(patient_id) %>% # 45 seconds
  select(-medication_id, -inpat_med, -bsa, -enc_type_c, 
         -department_id, -visit_fc, -contact_date, -event_time, 
         -hosp_admsn_type_c)

# for patients with treatment: make sure earliest row is selected
treatment_df <- med_and_dict_df
  group_by(patient_id) %>% add_tally(treatment) %>% ungroup() %>% 
  filter( !( n > 0 & treatment==F )    ) %>% 
  group_by(patient_id) %>% 
  summarise( order_time = min(order_time), 
                 treatment = max(treatment), 
                 hosp_admsn_time = first(hosp_admsn_time), 
                 hosp_disch_time = first(hosp_disch_time)
                 ) %>% 
  ungroup()

# CHECK: patient_id==1: order_time=="2015-02-05"
# CHECK: patient_id==271815 => "2014-12-15 00:00:00"

# treatment_df <- med_and_dict_df %>% 
#   group_by(patient_id) %>% summarise_all(max) %>% 
#   ungroup()



write_csv(treatment_df, 
          path = "/Users/Tarun/Documents/BIO_RESEARCH/pull_data/treatment_df.csv"
          )

```

# Merge in cohort 
## Tables: dx_master

```{r diagnoses}

# Filter for 3 auto-immune conditions
# Autoimmune Hypothyroidism
# Celiac
# T1DM

dx_df <- con %>%
  tbl("dx_master") %>% 
  filter(dx_hospital=="SHC" & year(contact_date_time) >= 2009) %>% 
  select(patient_id, contact_date_time, code, code_source) %>% 
  collect()

write_csv(dx_df, 
          "/Users/Tarun/Documents/BIO_RESEARCH/pull_data/dx_df.csv"  
          )

# Mark all diagnoses that are correspond to outcomes
dx_df <- read_csv("/Users/Tarun/Documents/BIO_RESEARCH/pull_data/dx_df.csv")
# 41 seconds

# Load the diagnosis codes from diagnoses.Rmd
load( "/Users/Tarun/Documents/BIO_RESEARCH/diagnoses/diagnosis_codes" )

dx_icd9 <- dx_df %>% 
  filter( code_source=="ICD9CM" ) %>% 
  mutate( dx_autoth = ( code == auto_hypo_icd9  ) ) %>% 
  mutate( dx_celiac = ( code == celiac_icd9 ) ) %>% 
  mutate( dx_t1dm   = ( code %in% t1dm_icd9 ) )

dx_dxid <- dx_df %>% 
  filter( code_source=="DX_ID" ) %>% 
  mutate( dx_autoth = ( code %in% auto_hypo_dx_id  ) ) %>% 
  mutate( dx_celiac = ( code %in% celiac_dx_id ) ) %>% 
  mutate( dx_t1dm   = ( code %in% t1dm_dx_id ) )

dx_outcome_df <- dx_icd9 %>%  
  bind_rows(dx_dxid) %>% 
  filter( dx_autoth | dx_celiac | dx_t1dm ) %>% # keep only patients with at least one outcome
  arrange(patient_id, contact_date_time) %>% 
  select(patient_id, contact_date_time, starts_with("dx"))



# Merge the diagnosis/outcome data onto the treatment_df table
treatment_df <- read_csv("/Users/Tarun/Documents/BIO_RESEARCH/pull_data/treatment_df.csv")

treatment_df <- treatment_df %>% 
  select(patient_id, order_time, treatment)

# Keep only diagnoses that happen after index date of BSA
# cohort_diag_df <- treatment_df %>% 
#   left_join(dx_outcome_df, by="patient_id") %>% 
#   replace_na( list(dx_autoth=F, dx_celiac=F, dx_t1dm = F) ) %>% 
#   mutate( early_diag =
#             !is.na(contact_date_time) & 
#             floor_date(contact_date_time, unit = "days") <= order_time + 4*dweeks(x=1) ) %>%
#   replace_na( list(early_diag=F) ) %>% 
#   mutate( contact_date_time = 
#             ifelse( early_diag==T , NA, as.numeric(contact_date_time)  )  ) %>% 
#   mutate(contact_date_time = as_date(contact_date_time)) %>% 
#   mutate( dx_autoth = ifelse(early_diag & dx_autoth, F, dx_autoth  )   ) %>% 
#   mutate( dx_celiac = ifelse(early_diag & dx_celiac, F, dx_celiac  )   ) %>% 
#   mutate( dx_t1dm   = ifelse(early_diag & dx_t1dm, F, dx_t1dm  )   ) %>% 
#   select(-early_diag) 


cohort_diag_df <- treatment_df %>% 
  left_join(dx_outcome_df, by="patient_id") %>% 
  replace_na( list(dx_autoth=F, dx_celiac=F, dx_t1dm = F) ) %>% 
  mutate( early_diag =
            !is.na(contact_date_time) & 
            floor_date(contact_date_time, unit = "days") <= order_time + 4*dweeks(x=1) ) %>%
  replace_na( list(early_diag=F) ) 

foo <- cohort_diag_df %>% 
  filter(early_diag==T) %>% 
  mutate( contact_date_time = as.POSIXct(NA) )

bar <- cohort_diag_df %>% 
  filter(early_diag==F)

cohort_diag_df <- foo %>% 
  bind_rows(bar) %>% 
  mutate( dx_autoth = ifelse(early_diag & dx_autoth, F, dx_autoth  )   ) %>%
  mutate( dx_celiac = ifelse(early_diag & dx_celiac, F, dx_celiac  )   ) %>%
  mutate( dx_t1dm   = ifelse(early_diag & dx_t1dm, F, dx_t1dm  )   ) %>%
  select(-early_diag)
  
str(cohort_diag_df)
head(filter(cohort_diag_df, !is.na(contact_date_time)), n = 50 )

# View(filter(cohort_diag_df, !is.na(contact_date_time) ))
# print(paste0("Early diags: ", sum(cohort_diag_df$dx_autoth) - sum(foo$dx_autoth) ,
#              " Out of: ", sum(cohort_diag_df$dx_autoth) ))
# print(paste0("Early diags: ", sum(cohort_diag_df$dx_celiac) - sum(foo$dx_celiac) ,
#              " Out of: ", sum(cohort_diag_df$dx_celiac) ))
# print(paste0("Early diags: ", sum(cohort_diag_df$dx_t1dm) - sum(foo$dx_t1dm) ,
#              " Out of: ", sum(cohort_diag_df$dx_t1dm) ))

# Split by outcome
cohort_none_df <- cohort_diag_df %>% 
  mutate( sum_dx = dx_autoth + dx_celiac + dx_t1dm ) %>% 
  group_by(patient_id) %>% filter(max(sum_dx)==0) %>% 
  ungroup() %>% select(-sum_dx) %>% 
  mutate(dx_none = T)
  
cohort_autoth_df <- cohort_diag_df %>% 
  filter(dx_autoth) %>% group_by(patient_id) %>% 
  # for each patient, assign first diagnosis based on contact_date_time
  filter(contact_date_time == min(contact_date_time) ) %>% ungroup() %>% 
  filter(!duplicated(.)) # some diagnoses happened simultaneously

cohort_celiac_df <- cohort_diag_df %>% 
  filter(dx_celiac) %>% group_by(patient_id) %>% 
  filter(contact_date_time == min(contact_date_time)) %>% ungroup() %>% 
  filter(!duplicated(.))
  
cohort_t1dm_df <- cohort_diag_df %>% 
  filter(dx_t1dm) %>% group_by(patient_id) %>% 
  filter(contact_date_time == min(contact_date_time)) %>% ungroup() %>% 
  filter(!duplicated(.))
    
# Combine back together
cohort_df <- cohort_none_df %>% 
  bind_rows( cohort_autoth_df, cohort_celiac_df, cohort_t1dm_df ) %>% 
  replace_na(list(dx_none = F))

write_csv( cohort_df, 
           "/Users/Tarun/Documents/BIO_RESEARCH/pull_data/cohort_df.csv" 
           )

```

