---
title: "pull_features"
author: "Tarun"
date: "3/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dbplyr)
library(RMySQL)
library(tidyverse)
library(lubridate)

con <- dbConnect(MySQL(),  
                 user="tnarasim",
                 password=rstudioapi::askForPassword("Database password"), 
                 host="shahlab-db1.stanford.edu", 
                 port=3306,
                 db = "stride7"
)

```

# Open cohort dataframe
```{r}

cohort_df <- read_csv("/Users/Tarun/Documents/BIO_RESEARCH/pull_data/cohort_df.csv")

```


# Merge in demographics

```{r demographics}

demo_df <- con %>% 
  tbl("demographics") %>% 
  select(patient_id, race, gender, ethnicity, birth_date) %>% 
  collect()
dbDisconnect(con)

features_df <- cohort_df %>% 
  left_join(demo_df, by = "patient_id")

write_csv(features_df, "/Users/Tarun/Documents/BIO_RESEARCH/pull_data/features_df.csv")

```


# Merge in medications features

```{r}
## Analyses for Tavpritesh

hist_df <- con %>% 
  tbl("SHC_med_de") %>% 
  select(end_time, discon_time) %>% 
  collect() # 4 minutes

hist_df_plot <- hist_df %>% 
  sample_frac(0.1) 

n_discon <- nrow(filter(hist_df, discon_time!="0000-00-00 00:00:00"  ))/nrow(hist_df)
n_end <-nrow(filter(hist_df, end_time!="0000-00-00 00:00:00"  ))/nrow(hist_df)

foo <- hist_df_plot %>% 
  filter(end_time != "0000-00-00 00:00:00") %>% 
  mutate( x = as.POSIXct( strptime(end_time,"%Y-%m-%d %H:%M:%S") ), 
          y = as.POSIXct( strptime(discon_time,"%Y-%m-%d %H:%M:%S") ))
  
bar <- foo %>% 
  mutate( difftime = int_length( interval( x, y ) )/(24*60*60) )

q <- quantile(bar$difftime, probs = c(0.01,0.99), na.rm = T )
bar2 <- filter( bar, difftime >= q[1] & difftime <= q[2]  )  
ggplot(bar2, aes(difftime) ) + geom_histogram(bins=50) + 
  ggtitle("discon_time - end_time") + xlab("Days")


```


```{r medications}
# Pull data

med_features_df <- con %>% 
  tbl("SHC_med_de") %>% 
  select(patient_id, 
          medication_id, 
          start_time, 
          end_time, 
          order_time, 
          med_route_c, 
          quantity,
          refills, 
          hv_dose_unit_c, 
          hv_discrete_dose) %>% 
  collect() %>% 
  right_join(cohort_df, by=c("patient_id", "order_time", "medication_id"))


# merge on drug features
#   using patient_id, order_time, medication_id



# calculate duration as interval(order_time, end_time)
#  take care of instances where end_time < order_time 
```

